# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount
#baseurl: http://ytaowang.github.com/blog

# configuration required for some pages

domain: blog.example.com
title: Just a blog
author: wyt
email: yt0907.Wang@gmail.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

  github:
    username: ytaoWang

  disqus:
    id: ytaowang
